export const drivers = {
  GET_DRIVERS: 'GET_DRIVERS',
  ERROR_DRIVERS: 'ERROR_DRIVERS',
  GET_DRIVERS_SCROLLING: 'GET_DRIVERS_SCROLLING',
  FOOTER_LOADING: 'FOOTER_LOADING',
  LOADING_DRIVERS: 'LOADING_DRIVERS',
};
